In [5]:
import pandas as pd
import sqlite3

In [7]:
telco_data = pd.read_csv("../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")
print(telco_data.shape)

(7043, 21)

In [9]:
connection = sqlite3.connect("../data/processed/customer_analytics.db")
print("database connected")

database connected

In [11]:
telco_data.to_sql("customers", connection,if_exists="replace", index=False)
print("Customer data loaded into customer table")

Customer data loaded into customer table

#### Total number of customers

In [15]:
query = """
SELECT COUNT(*) AS total_customers
FROM customers;
"""
result = pd.read_sql_query(query, connection)
result

   total_customers
0             7043

#### Churned Customers

In [16]:
query = """
SELECT *
FROM customers
WHERE Churn = 'Yes';
"""

pd.read_sql_query(query, connection)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
1,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
2,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
3,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
4,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1864,1699-HPSBG,Male,0,No,No,12,Yes,No,DSL,No,...,No,Yes,Yes,No,One year,Yes,Electronic check,59.80,727.8,Yes
1865,8775-CEBBJ,Female,0,No,No,9,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),44.20,403.35,Yes
1866,6894-LFHLY,Male,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
1867,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
1868,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes

#### Customers who did not churn

In [17]:
query = """
SELECT *
FROM customers
WHERE Churn = 'No';
"""

pd.read_sql_query(query, connection)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
3,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
4,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5169,2569-WGERO,Female,0,No,No,72,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No
5170,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
5171,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
5172,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
5173,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

#### Month-to-month customers

In [18]:
query = """
SELECT *
FROM customers
WHERE Contract = 'Month-to-month';
"""

pd.read_sql_query(query, connection)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
2,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
3,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
4,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3870,9767-FFLEM,Male,0,No,No,38,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),69.50,2625.25,No
3871,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
3872,8456-QDAVC,Male,0,No,No,19,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),78.70,1495.1,No
3873,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
3874,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes

#### High monthly charges

In [19]:
query = """
SELECT customerID, tenure, MonthlyCharges, Churn
FROM customers
WHERE MonthlyCharges > 100;
"""

pd.read_sql_query(query, connection)

     customerID  tenure  MonthlyCharges Churn
0    7892-POOKP      28          104.80   Yes
1    8091-TTVAX      58          100.35    No
2    0280-XJGEX      49          103.70   Yes
3    5129-JLPIS      25          105.50    No
4    3655-SNQYZ      69          113.25    No
..          ...     ...             ...   ...
897  7203-OYKCT      72          104.95    No
898  1035-IPQPU      63          103.50    No
899  0639-TSIQW      67          102.95   Yes
900  2234-XADUH      72          103.20    No
901  3186-AJIEK      66          105.65    No

[902 rows x 4 columns]

#### Fiber optic customers

In [20]:
query = """
SELECT customerID, InternetService, MonthlyCharges, Churn
FROM customers
WHERE InternetService = 'Fiber optic';
"""

pd.read_sql_query(query, connection)

      customerID InternetService  MonthlyCharges Churn
0     9237-HQITU     Fiber optic           70.70   Yes
1     9305-CDSKC     Fiber optic           99.65   Yes
2     1452-KIOVK     Fiber optic           89.10    No
3     7892-POOKP     Fiber optic          104.80   Yes
4     8091-TTVAX     Fiber optic          100.35    No
...          ...             ...             ...   ...
3091  0639-TSIQW     Fiber optic          102.95   Yes
3092  8456-QDAVC     Fiber optic           78.70    No
3093  2234-XADUH     Fiber optic          103.20    No
3094  8361-LTMKD     Fiber optic           74.40   Yes
3095  3186-AJIEK     Fiber optic          105.65    No

[3096 rows x 4 columns]

#### Churned + high monthly charges

In [21]:
query = """
SELECT customerID, tenure, MonthlyCharges, Contract, Churn
FROM customers
WHERE Churn = 'Yes'
AND MonthlyCharges > 100;
"""

pd.read_sql_query(query, connection)

     customerID  tenure  MonthlyCharges        Contract Churn
0    7892-POOKP      28          104.80  Month-to-month   Yes
1    0280-XJGEX      49          103.70  Month-to-month   Yes
2    5380-WJKOV      34          106.35  Month-to-month   Yes
3    3192-NQECA      68          110.00        Two year   Yes
4    5299-RULOA      10          100.25  Month-to-month   Yes
..          ...     ...             ...             ...   ...
248  6394-MFYNG      48          107.40  Month-to-month   Yes
249  0886-QGENL      27          101.25  Month-to-month   Yes
250  6664-FPDAC      56          111.95        One year   Yes
251  0093-XWZFY      40          104.50  Month-to-month   Yes
252  0639-TSIQW      67          102.95  Month-to-month   Yes

[253 rows x 5 columns]

#### Average monthly charges

In [22]:
query = """
SELECT AVG(MonthlyCharges) AS average_monthly_charges
FROM customers;
"""

pd.read_sql_query(query, connection)

   average_monthly_charges
0                64.761692

#### Churn by contract

In [23]:
query = """
SELECT Contract, Churn, COUNT(*) AS customer_count
FROM customers
GROUP BY Contract, Churn
ORDER BY Contract;
"""

pd.read_sql_query(query, connection)

         Contract Churn  customer_count
0  Month-to-month    No            2220
1  Month-to-month   Yes            1655
2        One year    No            1307
3        One year   Yes             166
4        Two year    No            1647
5        Two year   Yes              48

#### Churn By Payment Method

In [24]:
query = """
SELECT PaymentMethod, Churn, COUNT(*) AS customer_count
FROM customers
GROUP BY PaymentMethod, Churn
ORDER BY PaymentMethod;
"""

pd.read_sql_query(query, connection)

               PaymentMethod Churn  customer_count
0  Bank transfer (automatic)    No            1286
1  Bank transfer (automatic)   Yes             258
2    Credit card (automatic)    No            1290
3    Credit card (automatic)   Yes             232
4           Electronic check    No            1294
5           Electronic check   Yes            1071
6               Mailed check    No            1304
7               Mailed check   Yes             308

#### Average Total Charges

In [25]:
query = """
SELECT AVG(CAST(TotalCharges AS REAL)) AS average_total_charges
FROM customers;
"""

pd.read_sql_query(query, connection)

   average_total_charges
0            2279.734304

#### Long-tenure customers

In [26]:
query = """
SELECT customerID, tenure, Contract, MonthlyCharges, Churn
FROM customers
WHERE tenure >= 60
ORDER BY tenure DESC;
"""

pd.read_sql_query(query, connection)

      customerID  tenure        Contract  MonthlyCharges Churn
0     5248-YGIJN      72        Two year           90.25    No
1     6234-RAAPL      72        Two year           99.90    No
2     5954-BDFSG      72        Two year          107.50    No
3     0526-SXDJP      72        Two year           42.10    No
4     9848-JQJTX      72        Two year          100.90    No
...          ...     ...             ...             ...   ...
1478  8782-NUUOL      60        One year           79.00    No
1479  1150-FTQGN      60        One year           94.15    No
1480  9330-VOFSZ      60        Two year          110.80    No
1481  4940-KHCWD      60        Two year           37.70    No
1482  1036-GUDCL      60  Month-to-month           79.05    No

[1483 rows x 5 columns]

#### Customer segments based on services

In [27]:
query = """
SELECT InternetService, Contract, COUNT(*) AS customer_count
FROM customers
GROUP BY InternetService, Contract
ORDER BY customer_count DESC;
"""

pd.read_sql_query(query, connection)

  InternetService        Contract  customer_count
0     Fiber optic  Month-to-month            2128
1             DSL  Month-to-month            1223
2              No        Two year             638
3             DSL        Two year             628
4             DSL        One year             570
5     Fiber optic        One year             539
6              No  Month-to-month             524
7     Fiber optic        Two year             429
8              No        One year             364

#### Revenue-related analysis

In [28]:
query = """
SELECT Contract, COUNT(*) AS customer_count, SUM(MonthlyCharges) AS total_monthly_revenue, AVG(MonthlyCharges) AS average_monthly_revenue
FROM customers
GROUP BY Contract
ORDER BY total_monthly_revenue DESC;
"""

pd.read_sql_query(query, connection)

,Contract,customer_count,total_monthly_revenue,average_monthly_revenue
0,Month-to-month,3875,257294.15,66.398490
1,Two year,1695,103005.85,60.770413
2,One year,1473,95816.60,65.048608